# Mi aplicación de gestión de eventos
spring.application.name=eventos-api

# Me conecto a la base de datos en la nube (Supabase).
# OJO: Agregué 'prepareThreshold=0' al final de la URL porque PgBouncer me estaba dando problemas con los prepared statements.
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0

# Las credenciales de acceso a mi instancia de Supabase
spring.datasource.username=postgres.opjompxkybcelvwgyegj
spring.datasource.password=GreenEvents2026*

# Configuración de Hibernate para interactuar con PostgreSQL
# Uso 'update' para que las tablas se creen o actualicen solas según mis entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Activo esto para ver las consultas SQL limpias y formateadas en la consola mientras desarrollo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Truco vital para Hikari y PgBouncer: Fuerzo a que no se guarde caché de consultas en el pooler.
# Esto me evita el maldito error "prepared statement already exists".
spring.datasource.hikari.data-source-properties.prepareThreshold=0

# Cambio el puerto por defecto de Spring Boot al 8181 para evitar conflictos
server.port=8181